projects:
  qsfphotofeed:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - amplify/**
    extensions:
      amplify:
        graphQLApiId: tyfqyjbue5c5fp6ddjinfwtmei
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
