// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:142f16ac-c44c-4132-816b-01c9c0c7db57",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_6IR0Korcz",
    "aws_user_pools_web_client_id": "6aka97tqe1u5qdb2u6e84q6aki",
    "aws_user_files_s3_bucket": "qsfphotofeed5899d9c121a84fc1b8aa4ba193396673",
    "aws_user_files_s3_bucket_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://rt3uti6ppffkdjlrynlafevs6u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-loekarlb3zac5oxnb2p5ri7glq"
};


export default awsmobile;
